#!/usr/bin/env python3
"""
build_phase_images.py
─────────────────────
Converts per-phase pin images into base64 data URLs and writes them to
data/phase_images.js, which the app loads automatically.

Run this script any time you add or replace a phase image:
    cd vivekananda_map/data
    python3 build_phase_images.py

Expected filenames in data/images/:
    phase_p1.jpg  (or .jpeg / .png)  → Early Life & Indian Wandering
    phase_p2.jpg                     → First Western Tour
    phase_p3.jpg                     → Return to India & Mission Building
    phase_p4.jpg                     → Second Western Tour
    phase_p5.jpg                     → Final Years in India
"""

import base64
import json
import os

PHASES      = ['p1', 'p2', 'p3', 'p4', 'p5']
EXTENSIONS  = ['.jpg', '.jpeg', '.png', '.webp']
IMAGES_DIR  = os.path.join(os.path.dirname(__file__), 'images')
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), 'phase_images.js')

def mime_for(ext):
    return 'image/png' if ext == '.png' else ('image/webp' if ext == '.webp' else 'image/jpeg')

data = {}
for phase in PHASES:
    for ext in EXTENSIONS:
        path = os.path.join(IMAGES_DIR, f'phase_{phase}{ext}')
        if os.path.exists(path):
            with open(path, 'rb') as f:
                b64 = base64.b64encode(f.read()).decode()
            data[phase] = f'data:{mime_for(ext)};base64,{b64}'
            print(f'  ✓ {phase}  ←  phase_{phase}{ext}  ({os.path.getsize(path)//1024} KB)')
            break
    else:
        print(f'  –  {phase}  (no image found, will use colour pin)')

found = list(data.keys())
js = (
    '// Auto-generated by build_phase_images.py — do not edit manually.\n'
    '// Re-run the script after adding or replacing phase images.\n'
    f'// Contains: {found if found else "none"}\n'
    'window.PHASE_IMAGES_DATA = ' + json.dumps(data) + ';\n'
)

with open(OUTPUT_FILE, 'w') as f:
    f.write(js)

print(f'\nWrote phase_images.js  ({len(found)}/5 phases have images)')
